---
# Start HDFS related JVM
# Starting service with following order(JournalNode -> NameNode -> ZKFC -> Secondary NameNode -> DataNode)
# https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.4.2/bk_HDP_Reference_Guide/content/starting_hdp_services.html

- hosts: pbdpce01
  sudo: True
  vars_files:
  - vars/main.yml

  tasks:
  - include: tasks/ctl_journalnode.yml ctl_action=started
  - include: tasks/ctl_namenode.yml ctl_action=started
  - include: tasks/ctl_zkfc.yml ctl_action=started
  - include: tasks/ctl_secondarynamenode.yml ctl_action=started
  - include: tasks/start-datanode.yml ctl_action=started